### ISSUE TITLE
Update MSE & EME editor list

### ISSUE THREAD

**Issue by mounirlamouri** [w3c/media-wg#10]
The list at the moment is the following:

**MSE**
 - Matt Wolenetz, Google
 - Mark or Greg from Netflix
 - Maybe someone from Microsoft

**EME**
 - Joey Parrish, Google
 - Mark or Greg from Netflix
 - Maybe someone from Microsoft

The Microsoft question is being addressed in #9.

@mwatson2, can you remind me who is going to edit what on the Netflix side?

**Comment by mwatson2** [comment]
I will stay on as co-editor for MSE and Greg Freedman (gregwf@netflix.com) will take over as co-editor for EME.
