### ISSUE TITLE
TPAC F2F 2020

### ISSUE THREAD

**Issue by mounirlamouri** [w3c/media-wg#13]
Should we meet at the TPAC F2F if it happens? For how long? Should we host a WebCodecs discussion?

**Comment by tidoust** [comment]
Discussed during the [Media WG call on 12 May 2020](https://www.w3.org/2020/05/12-mediawg-minutes.html#t02).

**Resolution:** We will meet at TPAC 2020 and include WebCodecs as a joint session with the WICG (see [minutes](https://www.w3.org/2020/05/12-mediawg-minutes.html#r02))

**Comment by tidoust** [comment]
W3C confirmed yesterday that there will be no in-person TPAC 2020, so meeting will be virtual (details to follow later on). One consequence is that meeting dates for the group are no longer imposed: the group may choose to meet whenever and however it wants.

**Comment by mounirlamouri** [comment]
From the discussions during our previous meeting, we may meet at TPAC if we want to have a cross-group meeting. If we don't, our usual monthly meetings may be enough. One likely meeting would be with WebCodecs as it's not part of the group as of now and would be a good opportunity but this is TBD.
