### ISSUE TITLE
Triage MSE/EME issues

### ISSUE THREAD

**Issue by tidoust** [w3c/media-wg#16]
Both MSE and EME repos have an open set of issues flagged with "v1", "v1next" and other labels that were meaningful before these publications got published as Recommendations. It would be good to skim through them and identify those that the Media Working Group intends to address in the iteration of the spec it is working on, and those that go beyond the envisioned scope:
https://github.com/w3c/media-source/issues
https://github.com/w3c/encrypted-media/issues

**Comment by mounirlamouri** [comment]
Resolution: @wolenetz said they would triage the MSE issues while @joeyparrish will look at the EME ones.

**Comment by chrisn** [comment]
For those of us liaising with external groups for input on the v2 APIs, is there a rough deadline for when any issues or feature requests should be filed in order to be considered?

**Comment by mounirlamouri** [comment]
pinging @wolenetz and @joeyparrish for updates on this :)

**Comment by mounirlamouri** [comment]
Adding this to the agenda to attempt to do a triagging session at tomorrow's call.

**Comment by wolenetz** [comment]
I'll be on the call today. I expect bulk of MSE triaging will remain offline, and I'll get to those (in concert with @mwatson2) once the Chromium MSE-in-Workers experimental feature implementation lands (very soon now) (strongly related to https://github.com/w3c/media-source/issues/175).

**Comment by joeyparrish** [comment]
As of right now, about half of the open EME issues have a milestone assigned.  There are 19 which do not yet have a milestone: https://github.com/w3c/encrypted-media/issues?q=is%3Aopen+is%3Aissue+no%3Amilestone

**Comment by joeyparrish** [comment]
EME update post-triage:

18 open issues in the Backlog: https://github.com/w3c/encrypted-media/milestone/2
10 open features in V2: https://github.com/w3c/encrypted-media/milestone/5
12 open bugs/editorial issues in V2-Bugfixes: https://github.com/w3c/encrypted-media/milestone/6

**Comment by wolenetz** [comment]
MSE update post-trage (@mwatson2 and I finished triaging them Sept 28, 2020):

23 open issues in the Backlog: https://github.com/w3c/media-source/milestone/1
19 open features in V2: https://github.com/w3c/media-source/milestone/6
32 open bugs/editorial issues in V2BugFixes: https://github.com/w3c/media-source/milestone/7

As always, work group, community and API user input is very welcome. Please comment on existing issues or file new ones to help us further scope and evolve the V2 spec work.

**Comment by tidoust** [comment]
I believe that this issue has now been addressed, thanks to editors!
