### ISSUE TITLE
Joint meeting between CSS WG and Media WG

### ISSUE THREAD

**Issue by mounirlamouri** [w3c/media-wg#18]
After the regular agenda issues for the Media WG will be resolved, the rest of the Media WG meeting will be a join meeting with the CSS WG. If the regular agenda is small enough and not urgent, we may have the full meeting dedicated to the joint meeting and punt the other topics.

The topic will be: https://github.com/w3c/csswg-drafts/issues/5044

**Comment by astearns** [comment]
There are also some related comments in https://github.com/w3c/csswg-drafts/issues/5043
