### ISSUE TITLE
Privacy Review: Media Capabilities

### ISSUE THREAD

**Issue by mounirlamouri** [w3c/media-wg#23]
I was asked by Chris and others working on Media Capabilities to facilitate a privacy review with the PING.

The current status: waiting for them to confirm that the privacy & security questionnaire is up to date as it was updated 2 years ago.

**Comment by hober** [comment]
With my Security & Privacy Questionnaire editor hat on, it hasn't been published as a Note in a while but [the Editor's Draft](https://w3ctag.github.io/security-questionnaire/) has seen many updates over the last two years. Please feel free to use the ED.

**Comment by mounirlamouri** [comment]
As clarified in the Media WG meeting, I meant the questionnaire in the repository of Media Capabilities. The questionnaire is now up to date but I'm waiting for a change including some WebRTC information to land so the PING can look at a spec that's closer to what's actually being worked on.

**Comment by mounirlamouri** [comment]
Removing the agenda label as it was discussed at the January meeting.

**Comment by mounirlamouri** [comment]
The email was sent: https://lists.w3.org/Archives/Public/public-privacy/2021JanMar/0023.html
