### ISSUE TITLE
Move WebCodecs to the Media WG

### ISSUE THREAD

**Issue by mounirlamouri** [w3c/media-wg#24]
This is an issue meant to track the work being done:
- [x] Get Editors blessing
- [x] Send CfC for inclusion in the WG and FPWD to Media WG
- [x] Send Intent to Migrate to the WebCodecs repository.

@tidoust @jernoble

**Comment by mounirlamouri** [comment]
Media WG CfC: https://lists.w3.org/Archives/Public/public-media-wg/2021Feb/0000.html
Intent to Migrate: https://github.com/WICG/web-codecs/issues/130

**Comment by tidoust** [comment]
The Media WG [resolved to adopt WebCodecs](https://lists.w3.org/Archives/Public/public-media-wg/2021Mar/0004.html) as a normative deliverable. I'll work with editors to transition WebCodecs to the Media WG. Publication as First Public Working Draft will take place after the transition and once registry bits have been moved to a separate doc (see https://github.com/WICG/web-codecs/pull/149).

**Comment by tidoust** [comment]
Done and announced to the group at:
https://lists.w3.org/Archives/Public/public-media-wg/2021Mar/0006.html
