### ISSUE TITLE
Synchronize /TR documents with Editor's Drafts

### ISSUE THREAD

**Issue by tidoust** [w3c/media-wg#27]
As raised during [today's Media WG call](https://www.w3.org/2021/02/09-mediawg-minutes.html#t02), once a specification has been published to /TR, i.e. after publication of the spec as First Public Working Draft, the Editor's Draft can be kept in sync with the document in /TR automatically (through [Echidna](https://github.com/w3c/echidna/wiki)).

The main benefit is that there is no way to end up in the all-too-common situation where the document in /TR is way behind the latest Editor's Draft. One possible drawback is that the Editor's Draft may sometimes contain bits that do not yet represent the consensus of the whole group. Given how the Media Working Group operates, that seems unlikely to create issues, but YMMV...

For what it's worth, this has no implication with regards to the patent policy, as publications as First Public Working Draft, Candidate Recommendation Snapshots and final Recommendation remain gated by a group resolution at a minimum.

This issue is to assess support within the Media Working Group to use Echidna whenever possible for all the deliverables of the group.

**Comment by mounirlamouri** [comment]
Putting this in the agenda for the next call in case of no resolution is reached by then.

**Comment by tidoust** [comment]
The Media WG [resolved to synchronize /TR documents with Editor's Drafts](https://www.w3.org/2021/03/09-mediawg-minutes.html#t03). I'll work with editors to enable that.

**Comment by tidoust** [comment]
Deliverables published to /TR are all published automatically. Closing this issue accordingly.

**Comment by chrisn** [comment]
I found that the /TR link in the VideoFrame Metadata Registry isn't working:

* https://w3c.github.io/webcodecs/video_frame_metadata_registry.html
* https://www.w3.org/TR/webcodecs-video-frame-metadata-registry/

**Comment by tidoust** [comment]
Has there been a resolution to publish that registry as a Draft Registry under /TR already? I would need that to initiate the publication.

**Comment by chrisn** [comment]
I see, thanks. We don't yet, and it might be sensible to wait until we have at least the first registration ready to publish.
