### ISSUE TITLE
Rename default repo branches to "main"

### ISSUE THREAD

**Issue by tidoust** [w3c/media-wg#30]
We're progressively renaming default branches of W3C repositories to `main`. This is a meta issue to track Media WG repositories for which that still needs to happen:

- [x] [w3c/autoplay](https://github.com/w3c/autoplay)
- [x] [w3c/encrypted-media](https://github.com/w3c/encrypted-media)
- [x] [w3c/media-capabilities](https://github.com/w3c/media-capabilities)
- [x] [w3c/media-wg](https://github.com/w3c/media-wg)
- [x] [w3c/mediasession](https://github.com/w3c/mediasession)
- [x] [w3c/picture-in-picture](https://github.com/w3c/picture-in-picture)

Migration should be mostly transparent, except [branch names of local clones will have to be updated](https://docs.github.com/en/github/administering-a-repository/renaming-a-branch#updating-a-local-clone-after-a-branch-name-changes).

**Comment by joeyparrish** [comment]
Just completed migration of [w3c/encrypted-media](https://github.com/w3c/encrypted-media) branch name to "main".

**Comment by tidoust** [comment]
All done!
