### ISSUE TITLE
TPAC 2022 planning

### ISSUE THREAD

**Issue by chrisn** [w3c/media-wg#35]
After two years of virtual TPACs, the W3C team are looking at organizing a hybrid edition; physical meetings with strong support for remote participants. The physical meetings would be held in Vancouver from 12 to 16 September 2022.

Groups are being asked to gauge the level of interest and feasibility for an in-person meeting.

If we were to plan a hybrid Media WG meeting, would you want (or be able to) join in person in Vancouver? Please indicate your preference based on what you know today. We know things may change.

* :+1: if you plan to join in person
* :-1: if you can only join a virtual meeting
*  :confused: if you don't know at this stage

Please also comment to share any other feedback you may have. We'll share feedback with the W3C team later this month, so please reply before Friday 25 March.

**Comment by aboba** [comment]
I don't know at this stage. IMHO, if we are only talking about short meetings, it may be difficult to motivate travel (even though in my case, Vancouver CA is a modest drive from Seattle).

**Comment by chrisn** [comment]
W3C have confirmed that TPAC will be hybrid, as described above. It's up to individual groups how to use the time, we're not necessarily restricted to short meetings, but agendas should be scheduled so that anyone remote knows when to join.

**Comment by chrisn** [comment]
In addition, the TPAC planning questionnaire asks if we want to have a place for demos, and a developer meetup for the local community. Please reply here if you'd plan to attend and if you'd like to organise any demos.

**Comment by chrisn** [comment]
We need to confirm our plans to the TPAC organisers at W3C by 31 May.

A proposal: 

- One meeting (3 or 4 hours) dedicated to Media WG topics: overall spec status, prioritised issues against each of our specs
- One meeting (up to 3 hours) dedicated to joint topics with other groups (WebRTC, Media & Entertainment IG - DataCue proposal)

**Comment by chrisn** [comment]
Here's our current plan for TPAC 2022. We'll update this issue to develop the agenda.

- MEIG Meeting (Thursday 15th September 08:00 - 10:00 Pacific / 15:00 UTC - 17:00 UTC)
  - See https://github.com/w3c/media-and-entertainment/issues/83#issuecomment-1141259737 for agenda
- Audiovisual Media Formats Community Group (Thursday 15th September 13:30 - 15:00 Pacific / 20:30 - 22:00 UTC)
  - Agenda TBC
- Media WG / WebRTC WG / Media & Entertainment IG Joint Meeting (Thursday 15th September 15:30 - 17:30 Pacific / 22:30 - 00:30 UTC)
  - Agenda (see [slides](https://docs.google.com/presentation/d/1smFPi2EiVyKu21JVCxhziYvcmtHnm-uKHGgY7HwQkb4/edit))
    - 15:30 - 15:40 Welcome and introduction
    - 15:40 - 16:00 WebCodecs and RTCPeerConnection
    - 16:00 - 16:20 WebCodecs and WebRTC Encoded Transform
    - 16:20 - 16:40 WebCodecs and MediaCapture Transform
    - 16:40 - 17:00 WebCodecs and VideoFrame associated metadata
    - 17:00 - 17:20 WebCodecs AudioEncoder latency
    - 17:20 - 17:30 Media Capabilities and WebRTC
- Timed Text WG (Friday 16th September 08:00 - 13:00 Pacific / 15:00 - 20:00 UTC)
  - Includes Media WG joint meeting (12:00-13:00 Pacific). Topics:
    - Caption behavior with non-native controls
    - Video element updates around shadow DOM and containing content
- Media WG (Friday 16th September 14:00 - 18:00 Pacific / 21:00 - 01:00 UTC)
  - Agenda (see [slides](https://docs.google.com/presentation/d/1zYCIVHyvaGxIppC3OYFYfWWIwNnecPu6ikCg9GtqZ9Y/edit))
    - 14:00 - 14:10 Welcome and introduction
    - 14:10 - 15:00 Media Source Extensions issues and v2 feature prioritisation
    - 15:00 - 15:30 Encrypted Media Extensions issues
    - 15:30 - 16:00 Break
    - 16:00 - 16:30 WebCodecs issues
    - 16:30 - 16:45 Autoplay Policy Detection issues
    - 16:45 - 17:30 Media Session and Audio Focus issues
    - 17:30 - 18:00 Document Picture in Picture introduction and Q&A

All meetings will be hybrid, with both in-person and remote participation.

**Comment by chcunningham** [comment]
For the specs I co-edit I don't have any specific agenda yet. I meet w/ @aboba and @padenot pretty regularly to go over issues and PRs (though I'm OOO a lot this summer - new baby).

**Comment by chrisn** [comment]
The TPAC agenda for the Media WG meeting and joint meeting with WebRTC WG and MEIG is mostly complete. Please review and reply here if you have any suggested additions or alterations. Thanks!

**Comment by tidoust** [comment]
Links to the minutes of the meetings mentioned above:
- [Media & Entertainment IG](https://www.w3.org/2022/09/15-me-minutes.html)
- [Audiovisual Media Formats Community Group](https://www.w3.org/2022/09/15-audiofmts-minutes.html)
- [Media WG / WebRTC WG / Media & Entertainment IG Joint Meeting](https://www.w3.org/2022/09/15-mediawg-minutes.html)
- [Timed Text WG](https://www.w3.org/2022/09/16-tt-minutes.html)
- [Media WG](https://www.w3.org/2022/09/16-mediawg-minutes.html)

**Comment by chrisn** [comment]
Thank you @tidoust for collating all the minutes! And thank you to everyone who participated at TPAC.
