### ISSUE TITLE
October 11 Media WG meeting

### ISSUE THREAD

**Issue by chrisn** [w3c/media-wg#37]
I've just posted an [invite and agenda](https://lists.w3.org/Archives/Public/public-media-wg/2022Oct/0000.html)  for a Media WG meeting next week (Tuesday 11 Oct at 9am Pacific), with some MSE interop issues that @wolenetz has suggested.

But, the meeting overlaps with FOMS. Matt has said he's available, but wondering whether to reschedule or change the agenda depending on who's available.

@jernoble Are you available for this WG meeting? 

@karlt - I notice that you're not a member of Media WG, so possibly aren't receiving meeting invites. Are you also available? There's a link to join the WG [here](https://www.w3.org/groups/wg/media/join).

**Comment by karlt** [comment]
Thank you, @chrisn.  I have recently joined the Media WG and so did get an invite.  I probably wouldn't attend the meeting.

I have previously written [some thoughts about perhaps getting Firefox to play through gapless audio](https://bugzilla.mozilla.org/show_bug.cgi?id=1762976).  I don't have much concrete to add to spec direction beyond what @wolenetz has [summarized well](https://github.com/w3c/media-source/issues/160#issuecomment-537611953).

FWIW I'm in UTC+13 but recognize that any time is difficult for at least someone.
