### ISSUE TITLE
Send a CfC for FPWD for Picture-in-Picture, Media Session, and Media Capabilities

### ISSUE THREAD

**Issue by mounirlamouri** [w3c/media-wg#4]
/CC @jernoble @tidoust

**Comment by tidoust** [comment]
According to the [timeline in the charter](https://www.w3.org/2019/05/media-wg-charter.html#timeline), the group is a late for these specifications. That is not a huge deal, but I don't really see any good reason to delay things further:
1. overall, these specifications are already in "good shape";
2. although they will undergo further substantive changes, they don't contain features that have been identified as blatantly wrong;
3. publication as a First Public Working Draft does not set things in stone in any case.

Main benefit of publishing a First Public Working Draft is that it triggers a Call for Exclusions (see [section 6.3.1 in the W3C Process](https://www.w3.org/2019/Process-20190301/#first-wd)).

@mounirlamouri @jernoble May I go ahead and issue calls for consensus in respective repositories to gather people's approval and/or list issues that people may want to see addressed before the specs get published?

**Comment by mounirlamouri** [comment]
I think these three specifications are definitely ready for a FPWD. I'm happy to have the CfC sent out. Is there anything I can do to help?

**Comment by jernoble** [comment]
I agree with @mounirlamouri. Happy to have the CfC sent out.

**Comment by tidoust** [comment]
OK, I created individual calls for consensus for each spec:
https://github.com/w3c/media-capabilities/issues/142
https://github.com/w3c/picture-in-picture/issues/173
https://github.com/w3c/mediasession/issues/246

... and raised it on the mailing-list as well:
https://lists.w3.org/Archives/Public/public-media-wg/2020Jan/0000.html

Deadline for voicing objections is **January 24th 2020**.

@mounirlamouri I believe that's all that is needed for now (I'll check pubrules and may issue a couple of pull requests against the specs, but nothing fancy).
