### ISSUE TITLE
TPAC 2023 planning

### ISSUE THREAD

**Issue by chrisn** [w3c/media-wg#40]
TPAC 2023 is planned to be held in Seville from 11 to 15 September 2023. These will be hybrid meetings with in-person and remote attendance, as last year.

Groups are being asked to give an indication of their meeting plans, by 8 May.

My suggestion would be we do the same as last year: 4 hours of meetings, in two 2-hour sessions.

If we were to plan a hybrid Media WG meeting, would you want (or be able to) join in person in Seville? 

Please indicate your preference on whether you'd plan to travel. This is to get a sense of the number of people who would be there in person, so we have an appropriate sized room. I realize this is very early, so not looking for you to commit right now.

* :+1: if you would plan to join in person
* :-1: if you can only join a virtual meeting

We can also organize joint meetings with other groups as needed, such as Audio WG, Web RTC WG, Timed Text WG, Media & Entertainment IG, Please leave a comment with your suggestions.

**Comment by nigelmegitt** [comment]
I would propose that we try to schedule media-related topics at the beginning of the week to allow travel time for any folk heading to Amsterdam for IBC (begins on the Friday of TPAC week).

**Comment by chrisn** [comment]
I agree. I also would like to coordinate the requests for meeting times across the various media related groups. (I have emailed group chairs about that.)

**Comment by chrisn** [comment]
TPAC is planned for 11-15 September 2023.

Here is the planned schedule (all times are Central European Summer Time):

* Monday 11 September
  * Media WG meeting (14:30-16:30 and 17:00-18:30)
     * Agenda items (this is a draft, suggested alterations are welcome)
       * 14:30 - 14:35 Welcome and introduction
       * 14:35 - 15:10 WebCodecs
       * 15:10 - 15:40 Media Source Extensions (incl. Managed Media Source)
       * 15:40 - 16:10 Media Capabilities
       * 16:10 - 16:30 Encrypted Media Extensions
       * 16:30 - 17:00 Break
       * 17:00 - 17:40 Media Session
       * 17:40 - 17:50 Audio Session
       * 17:50 - 18:10 Web Video Filter API proposal
       * 18:10 - 18:30 Media Session Coordinator
     * Other topics (if time allows)
       * Autoplay Policy Detection
       * Picture in Picture

See [meeting slides](https://docs.google.com/presentation/d/1xANKmRNdkZqJCUnCOPz3HQ5xwyktI6sOswJ6x6z6bUo/edit) for detailed issues and topics within each agenda item.

There will also be meetings of related groups including: Media & Entertainment Interest Group, Timed Text WG, Audio WG, Second Screen WG, Audiovisual Media Formats CG.

We'll use this issue to develop the agenda, including joint meetings with other groups. Please reply here with suggestions or requests for agenda time.

**Comment by chrisn** [comment]
The TPAC schedule has been announced, and registration is open: https://www.w3.org/2023/09/TPAC/schedule.html

**Comment by marcoscaceres** [comment]
Joint meeting with WebRTC happening Friday September 15 at 14:30-16:30pm.

**Comment by marcoscaceres** [comment]
Last call for topics is this Friday the 4th of August! Agenda is pretty settled based on above. 

It would be great to have a list of issues for each spec. But getting status update on each spec would be amazing.

**Comment by aboba** [comment]
Potential topics for the joint MEDIA/WEBRTC WG meeting: 

1. Introduction (30 minutes)
    Streaming and RTC use cases
    Comparison of WebCodecs and WebRTC functionality
         Specific issues
           a. Codec support
                1. Differences in codec support
                2. Support for Machine learning
           b. SVC/simulcast support
           c. Rate control
           e. Hardware acceleration

2. Scalable Video Coding (30 minutes)
    a. Motivations for SVC support
    b. Status of SVC functionality in WebCodecs and WebRTC
    c. Potential work items and next steps

    Potential contributors/presenters:  Florent Castelli, Eugene Zemstov, Bernard Aboba, Harald Alvestrand

3. Codecs (30 minutes)
      a. Differences in codec support
      b. Machine learning-related coding standardization
      c.  Implications for WebRTC and WebCodecs

    Potential contributors/presenters:  Bernard, TBD (someone from AoMedia?)

4. Rate control (30 minutes)
         a. Rate control in WebRTC/WebCodecs
         b. Rate control use cases

**Comment by aboba** [comment]
A topic for the WebCodecs portion of the MEDIA WG meeting: 

- WebCodecs Container Format: https://datatracker.ietf.org/meeting/117/materials/slides-117-moq-webcodes-container-00

**Comment by chrisn** [comment]
The Media WG meeting agenda is pretty much complete. Please review the agenda above and [slides](https://docs.google.com/presentation/d/1xANKmRNdkZqJCUnCOPz3HQ5xwyktI6sOswJ6x6z6bUo/edit) and comment if you have any alterations.
