### ISSUE TITLE
TPAC 2024 Preparation

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/media-wg#47]
As we approach the W3C TPAC 2024, we wanted to share some important details regarding our upcoming face-to-face meeting:

**TPAC 2024 Dates:**
23-27 September 2024 - Anaheim, CA, USA - See: https://www.w3.org/news-events/w3c-tpac/

**Media Working Group Meetings:**

* Monday 23rd September 14:00-16:00 [Media WG and Immersive Web WG Joint Meeting](https://www.w3.org/events/meetings/388cffb5-7e88-4982-9e02-cb25c3703461/)
* Thursday, 26th September 11:00-12:30 [Media Working Group Meeting](https://www.w3.org/events/meetings/b3cc2ea2-1663-4282-a787-19dfa2cabba3/)
* Thursday, 26th September 14:00-16:00 [Web RTC Working Group and Media Working Group Joint Meeting](https://www.w3.org/events/meetings/b2c200b8-7362-4330-b74c-7b2efc05d87f/)
* Thursday, 26th September 16:30-18:00 [Media Working Group Meeting](https://www.w3.org/events/meetings/7d0047b9-8ccc-46d1-acdb-02adf726e67e/)
* Friday, 27th September 09:00-10:30 [Media Working Group Meeting](https://www.w3.org/events/meetings/9fa960e0-97e2-4a20-a2c7-d15b0752d6dd/)

To help us prepare for our meeting, we will be using the label "TPAC2024" on each repository to identify discussion topics. 

We are hoping to use the following three groupings for the topics:

1. Media WG specifications
2. Joint topics with other groups
3. Explorations or potential new topics/areas of interest

**Important Deadlines:**

- Please label all relevant issues by the **first week of September**.
- Chairs will put together the agenda by the **13th of September** to give everyone attending time to review the topics.

And don’t worry, we will send a periodic reminders through the next few months to remind everyone!

Nevertheless, we encourage everyone to start thinking about topics for discussion and to begin reaching out and coordinating among yourselves on the topics you would like to discuss face-to-face. September is not that far away. 

To ensure we have an appropriate room size, please indicate your attendance by giving a thumbs up on this issue.

If you have any questions or need further information, please do not hesitate to reach out.

Looking forward to seeing you at TPAC 2024!

**Comment by aboba** [comment]
Some potential topics for the WEBRTC/MEDIA WG joint meeting: 

- Common objects
- - VideoFrame registry
- - RTCEncodedXFrame Constructor vs. EncodedXChunk
- APIs
- - Media Capabilities API (privacy issues)
- Features
- - Alpha
- - Surround sound
- Long term goals
- - Encoder API update
- - WebCodecs + Transport as an alternative to WebRTC

**Comment by marcoscaceres** [comment]
Updated OP with relevant info.

**Comment by marcoscaceres** [comment]
@chrisn, I've added the TPAC2014 labels to each of the WG's repos.

**Comment by marcoscaceres** [comment]
@anssiko, @reillyeon, does one of the above days work for @w3c/das-wg? We could set aside 90mins to go through the joint deliverables.

**Comment by nigelmegitt** [comment]
Would like to avoid scheduling so it overlaps with TTWG please. Not sure if a joint meeting with TTWG would have any agenda items, but I'm open to it as Chair of TTWG.

**Comment by chrisn** [comment]
We included avoiding overlap with TTWG in our request for meeting time.

**Comment by chrisn** [comment]
Meeting schedule is now confirmed, details in the OP.

**Comment by marcoscaceres** [comment]
We've moved the agenda here: https://github.com/w3c/media-wg/wiki/TPAC-2024 ...
