### ISSUE TITLE
Investigate Mozilla editor for Media Session

### ISSUE THREAD

**Issue by mounirlamouri** [w3c/media-wg#6]
@padenot volunteered to look whether Mozilla would be interested to co-edit the Media Session specification. There are already two editors so there is no urgent need for a new one but wouldn't be bad either :)

**Comment by mounirlamouri** [comment]
ping @padenot

**Comment by padenot** [comment]
@alwu is going to edit this. @jernoble, @chrisn, we can probably close this.

**Comment by chrisn** [comment]
Thanks @padenot. Did you mean @alastor0325? There was a suggestion in the May Media WG meeting that we could find someone else to be co-editor in place of @mounirlamouri. I agree we can close and follow that up separately.

**Comment by alastor0325** [comment]
Yes, sorry my github account is different from my mozilla account name. I am happy to help on MediaSession as well.

**Comment by padenot** [comment]
Yes, my bad, `alwu` the name on internal Mozilla stuff, I meant @alastor0325. This is a bit more pressing since I think that  in practice the two editors are not involved in specs anymore.

**Comment by chrisn** [comment]
Yes, I hope @jernoble and @dalecurtis can suggest people to join Alastor as co-editors.

**Comment by dalecurtis** [comment]
I've passed this along internally to the team working on MediaSession.

**Comment by marcoscaceres** [comment]
Closing as Media Session has editors and active folks from Mozilla (though not editing).
