### ISSUE TITLE
Check potential MSFT editors for MSE and EME

### ISSUE THREAD

**Issue by mounirlamouri** [w3c/media-wg#9]
@scottlow said he will reach out internally. Microsoft used to have editors for these specifications but they are no longer around. Netflix and Google are willing to co-edit so we have two editors and there is no urgency to get a third.

**Comment by mounirlamouri** [comment]
ping @gregwhitworth :)

I see MSFT has an editor for Media Capabilities. During TPAC there were discussions around having MSFT replace Jerry Smith for EME and MSE. Both these specs already have 2 editors so there is no strong need for a third one but if you guys have bandwidth, I'm sure the help would be welcomed.

An okay feedback is that you don't want to contribute an editor at the moment and I can close this. You can always come back later when you are contributing more to these specs.

**Comment by gregwhitworth** [comment]
Yeah, I don't think we currently have the bandwidth for EME and MSE. We'll jump in for feedback as necessary and if we see that increase we may re-consider. Feel free to close and place Jerry Smith as previous editor.

**Comment by mounirlamouri** [comment]
Thank you for the update. I've sent https://github.com/w3c/media-source/pull/248 to update the status of the MSE spec. EME was already updated.

**Comment by wolenetz** [comment]
Thank you both for syncing on this. I've prepared an alternative to https://github.com/w3c/media-source/pull/248 which accomplishes the same intent in a more durable fashion (updates the source and the generated spec, not just the latter). See https://github.com/w3c/media-source/pull/249
